<a href="https://colab.research.google.com/github/bhuvanlekkala/bhuvanlekkala/blob/main/Bootcamp_Week_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("helo bhuvan")

helo bhuvan


**Comments**

In [ ]:
# bhuvan keep the pace and write the code

**OPERATORS-Arithmetic,Logical,Bitwise Etc**

In [ ]:
x=2
y=3
print(x+y) #Addition
print(x-y) #Subtraction
print(x*y) #Multiplication
print(x/y)  #Divide/division
print(x%y)  #modulus-remainder of division operated by left
print(x//y) #floor division result is whole no
print(x**y) #exponent-x to the power of y

5
-1
6
0.6666666666666666
2
0
8


Comparison Operator


In [ ]:
5<1 #compare two values 

False

In [ ]:
5>1 #gives True or False(Boolean type)

True

In [ ]:
"Bhuvan"<"achuth" #Computers can read numbers easily not alphabets thats why "" or '' is used for words or alphabets(Strings)

True

In [ ]:
# Comparison operators meaning
x>y #x Greater than y
x<y #x Less than y
x==y  #x equal to y
x!=y   #x not equal to y
x>=y   #x graterthan or equal to y
x<=y   #x lessthan or  equal to y

True

Logical operations

In [ ]:
x=3

x<1 and  x<7

False

In [ ]:
x=3
x<3 or x<5

True

In [ ]:
x=3


not(x<1 and x<7)

True

  Variables


In [ ]:
#Varibale is a container for storing values
x=5
y="bhuvan" 

Print Function



In [ ]:
#print is a function  will prints or shows the output inside parathesis or semicolans
print("bhuvan lekkala is great")

Input Function

In [ ]:
#input is a function used to get answer from question
x=input("bhuvan what is your age??")

bhuvan what is your age??22


Data Structures, Data Types and Strings in Python


Data structure is a data organization, management, and storage format that enables efficient access and modification. More precisely, a data structure is a collection of data values, the relationships among them, and the functions or operations that can be applied to the data.


In [ ]:
# type is used to know that type of data it is.
a=4
type(a)

int

In [ ]:
b=4.5
type(b)

float

In [ ]:
c="bhuvan"
type(c)

str

In [ ]:
boolvar=False
type(boolvar)

bool

Sequence Types-store multiple values in an organized and efficient way
(Step by step process so that it makes process easy and fast)

---




In [ ]:
#Accessing String Elements
a="bhuvan"
#indexing is to know the postion of character in a string by numbers starting from zer0(0)
print(a[0])


b


String Slicing
slicing is cutting of strings(letters)

In [ ]:
a="bhuvan lekkala"
# 7 is staring and 14 is ending and i just want only my surname not my name
print(a[7:14])

lekkala


Negative Indexing
it is same as indexing or slicing but from backwards

In [ ]:
a="bhuvan lekkala"
# it starts from -8 to last no not with 0 because -1 is last no and enterimg nothing refers to last no
#because 0 is fixed to something 
print(a[-8:])

 lekkala


String Concatenation


In [ ]:
x="bhuvan"
y="lekkala"
# concatination is adding strings #add with + sign
z=x+y
print(z)

bhuvanlekkala


String Concatenation: Add Space


In [ ]:
x="bhuvan"
y="lekkala"
# adding space for strings is same as words
print(x+" "+y)

bhuvan lekkala


String Length


In [ ]:
x="bhuvan lekkala"
# length function is used to find length(size) of string same as height
print(len(x))

14


Escaping Characters



In [ ]:
x="How are you doing today\"bhuvan?\""
#quotes are represented in "" but its defined so we use \"(backslash) to print same  
print(x)

How are you doing today"bhuvan?"


The in Syntax


In [ ]:
name="bhuvan lekkala"
# in is used to find weather letter or string is there in string
# gives the result as true or false
print("z" in name)
print("b" in name)

False
True


Iterate String


In [ ]:
name="bhuvan"
# this gives the every single character 
# any letter or element using in syntax referes to indexing and slicing from first to last:
for g in name:
    print(g)

b
h
u
v
a
n


Immutable String


In [ ]:
x=5
# immutable means no change ex:int,float,bool etc fixed, cannot be changed by user
print(type(x))

<class 'int'>


IndexError


In [ ]:
x="bhuvan"
# indexing is refernce just like book with pg no upto 200 
# if we call or check in index for 205 page then its error or false 
indx=x[4]

Python String .format()


In [ ]:
x="bhuvan is a {} boy"
# we use flowerbracketrs{} for change items just like scores
x.format("good")

'bhuvan is a good boy'

String Method .lower()


In [ ]:
x="BHUVAN LEKKALA"
# we use .lower to change to lower case letters
print(x.lower())

bhuvan lekkala


String Method .strip()


In [ ]:
x='................bhuvan ....lekkala......'
# we use this to remove spaces or anything from start and end of string
x.strip(".",)

'bhuvan ....lekkala'

String Method .title()


In [ ]:
x="bhuvan lekkala"
# we use this to change into capital letters for starting of words
x.title()

'Bhuvan Lekkala'

String Method .split()


In [ ]:
x="bhuvan lekkala"
# we use this method to split words or letters which we want to split(seperate)
x.split("a")

['bhuv', 'n lekk', 'l', '']

Python string method .find()


In [ ]:
x="bhuvan"
# we use this function to find indexing of element 
x.find("a")

4

String replace


In [ ]:
x="bhuvan"
# this replaces one with another first one is old, next is new
x.replace("a","A")

'bhuvAn'

String Method .upper()


In [ ]:
x="bhuvan"
# this replaces lower case to uppercase 
x.upper()

'BHUVAN'

String Method .join()


In [ ]:
x="bhuvan","is","a boy"
# this method is used to join different strings together with options
" ".join(x)


'bhuvan is a boy'


**Lists**





In [ ]:
x=["bhuvan","eats","chicken","biryani"]
#append means add and it adds at end
# lists are changable
x.append("with")
x.append("raitha")
print(x)

['bhuvan', 'eats', 'chicken', 'biryani', 'with', 'raitha']


In [ ]:
x=["bhuvan","eats","chicken","biryani"]
# insert with comming in the middle or adding in middle
# indexing is used to place on where we want to put it  
x.insert(2,"raitha")
x.insert(3,"with")
print(x)

['bhuvan', 'eats', 'raitha', 'with', 'chicken', 'biryani']


In [ ]:
x=["bhuvan","eats","chicken","biryani"]
y=["and","chapathi"]
# just like adding strings adding lists 
z=x+y
print(z)

['bhuvan', 'eats', 'chicken', 'biryani', 'and', 'chapathi']


In [ ]:
x=["bhuvan","eats","choclate" ,"5 star","choclate",]
#  it will count how many times which we want to search 
x.count("choclate")

2

In [ ]:
x=[55,99,35,89]
# it makes things in right place genrally ascending order(small to big)
# not apply for strings because these are words how??
x.sort()
print(x)

[35, 55, 89, 99]


**Tuple**

In [ ]:
# tuple is like exam once submitted cannot be changed
x=("bhuvan","eats",1,"chapathi")
# added by only concatination(adding) no append etc
y=("divesh","eats",2,"chapathi")
z=x+y
print(z)

('bhuvan', 'eats', 1, 'chapathi', 'divesh', 'eats', 2, 'chapathi')


In [ ]:
x=("bhuvan",)*3
# this behaves like a*b so we get bhuvan 3 times
print(x)

('bhuvan', 'bhuvan', 'bhuvan')

In [ ]:
x=(12,55544,89.3,45)
y=(36,55,68,3)
# max will give highest no
# min gives lowest no
print(max(x))
print(min(y))
# del means delete whole tuple
del(y)


55544
3


**Dictionary**

In [ ]:
# marks list gives people names and result
marks={}
# this gives the blank dictonary(table) which we can add any thing
marks["bhuvan"]=40
# the bracket value  reprsents key and right side after = gives value 
# just  like varibale= value
marks["divesh"]=75
marks["bhaskar"]=100
# bhuvan went for recorrection, bhuvan is fixed but marks may vary
marks["bhuvan"]=55
# checking names with marks
for key, value in marks.items():
    print("key:")
    print(key)
    print("value:")
    print(value)
    print("")


key:
bhuvan
value:
55

key:
divesh
value:
75

key:
bhaskar
value:
100



 **Functions and Packages**

In [ ]:
# function is rules given for input which may vary output
z="58"
# here int function used and changed string to integer
# change in small thing resulted something different
print(int(z))
# new one 
x=100
y=-100
# abs gives absolute value means positive value 
print(abs(y))
# if means condition starts 
# comapring means ==
# and function needs to end so colan(:)
if x==y:
    print("both are same")

58
100


In [ ]:
# round()
x=56.369
# rounding to near number but after,condition to 1 digit
round(x,1)
# sum() adding any collection of numbers
marks=(10,20,50,75)
print(sum(marks))

155


**Define Functions**


In [ ]:
# def represnts express the rules
# starting of function and end with colan(:) 
def pound_to_rupee(inr):
    money=inr*100
    print(money)
    # we can use function and repeat the process
pound_to_rupee(10)
pound_to_rupee(1)
pound_to_rupee(0.2)

1000
100
20.0


[**Methods**](https://)

In [ ]:
# Method is   function type for classifying objects
name="bhuvan"
# here name is called object and also variable
# It will have  the properties and behaviour
name.capitalize()

'Bhuvan'

**Is Methods and Functions same?**

In [ ]:
# All methods are functions, but not all functions are methods!\
family="bhuvan"
# Bhuvan is a type of family member

**Packages in Python**

In [ ]:
# packages is group of objects
university="Multiple of courses"
Courses="Course contains different modules"
modules="module contains different chapters"
# univeristy is package and courses and module is subpackages
# packages/modules are made by someone but used  to make developments

# **Arrays**

In [ ]:
# array is a collection of items just like lists but with same data types
# it will conatin only int, float, string etc in a data type


In [ ]:
# vectors is a type of array
# One dimensional array is a vector.
vector= [1, 2, 3, 4, 5]

In [ ]:
# Matrix is an arrangement of numbers into rows and columns
# matrix A has two rows and three columns, we write its shape as 2 X 3, pronounced as ‘two by three’


**NumPy**

In [ ]:
# Numpy is a library of numericals or numbers
# Just like libraries in colleges and schools 
# uses for refernce and also for get back and develop
# import numpy as np
# taking library and np is nick name jus like for humans

**Array in NumPy
**

In [ ]:
# array is data structure 
# data structure is a sequence or order for arranging the data
# ndarray is n-dimensional array eg:1d,2d,3d....nd
# vectors and matrices may had 1 or more dimesions

**Create NumPy Array from Python List
**

In [ ]:
bhuvan_marks=[40,55,68,75,99,100]
# list of marks 
import numpy as np
# lib import as nick name
np.marks=np.array(bhuvan_marks)
# nickname.any name=lib.data type(my list)
np.marks

array([ 40,  55,  68,  75,  99, 100])

**Compare Python List and NumPy Array
**

In [ ]:
# python list may contain any data typr but numpy contain same data type
# python takes more time and memory but numpy takes less time,steps and memory

**Numpy array type**

In [ ]:
import numpy as np
# take from lib as nick name
bhuvan=np.array([[1,2,3],[5,6,7],[8,99,45],[74,555,698]])
# nested list is a list having sublists
# the family is nested list having your family,relatives family and their relative family 
bhuvan
# print(bhuvan) is same as bhuvan in new line

array([[  1,   2,   3],
       [  5,   6,   7],
       [  8,  99,  45],
       [ 74, 555, 698]])

In [ ]:
bhuvan.size
# size of bhuvan contrains 12 elements

12

In [ ]:
bhuvan.dtype
# integer type and 64 bit computer and 32 bit depends on your computer
# 64 bit had more memory allocation than 32bit but if it works fine!

dtype('int64')

In [ ]:
bhuvan.shape
# shape is 4by3, 4(horizontal) rows and 3(vertical) columns

(4, 3)

In [ ]:
bhuvan.ndim
# dimensions is 2d like length*breadth

2

In [ ]:
type(bhuvan)
# type gives the what model it is.

numpy.ndarray

**arange**

In [ ]:
bhuvan=np.arange(10)
# collection of  continous integrs upto the entered value
bhuvan

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
bhuvan=np.zeros(10)
# creates 1dim zeros incl 10 digits
bhuvan

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
bhuvan=np.ones(3)
# array of 3 digits 1dim jus like zeros
bhuvan

array([1., 1., 1.])

In [ ]:
bhuvan=np.linspace(3,15,8)
# start=3,stop=15, num=upto 8 digits incl
# with out num it will gives 50 samples
bhuvan

array([ 3.        ,  4.71428571,  6.42857143,  8.14285714,  9.85714286,
       11.57142857, 13.28571429, 15.        ])

**Basic Methods, Reshaping and Slicing**

In [7]:
import numpy as np
# imprt lib 
bhuvan=np.array([2,3,89,6,7,9])
# append adds the number/item at last
np.append(bhuvan,36)

array([ 2,  3, 89,  6,  7,  9, 36])

In [8]:
# sort will arrange in ascending order
np.sort(bhuvan)

array([ 2,  3,  6,  7,  9, 89])

In [10]:
lekkala=np.arange(12)
# arange will sort numbers upto the entered value
lekkala

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
# arranging can be done for 12 in 3*4,4*3,6*2
np.reshape(lekkala,(6,2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.reshape(lekkala,(4,3))
# different types 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
from numpy.core.fromnumeric import ndim
b=np.array([12,45,98,8,19])
# positive indexing is done from o,1,2,..etc
# here 0 is 12, 1 is 45,2 is 98 
b[2]

98

In [34]:
np.ndim(2)

0

In [42]:
# postive indexing in 2d array left to right
b=np.array([[12,45,98],
            [7,8,19]])
# here it is 2d matrix type, 12 is (0,0) 45 is (0,1) indexing
b[1,2]

19

In [43]:
# same for the negative indexing
b=np.array([[1,2,5],
            [8,7,4]])
# starts from (-1,-1) is the last number same goes in right to left direction
b[-1,-1]

4

In [51]:
b=np.array([[1,2,3]
         ,[4,5,6]
         ,[7,8,9]
         ,[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
b[0:2:2]
# start with 0 incl 1st number and end upto last not incl last
# step 2 is upto [4,5,6] so its not including 

array([[1, 2, 3]])